name: Update Axelera RSS

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 06:00 UTC
  workflow_dispatch:     # allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate feed
        run: make gen_feeds

      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vperrin59/jobs-rss.git
          make deploy_feeds